services:

  ollama:
    image: ollama/ollama:latest
    container_name: devops-ollama

    ports:
      - "11434:11434"

    environment:
      OLLAMA_HOST: 0.0.0.0:11434

    volumes:
      - ollama_data:/root/.ollama

    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    image: devops-ai-backend:latest
    container_name: devops-ai-backend

    ports:
      - "8000:8000"

    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_CHAT_MODEL: llama3.1:8b
      OLLAMA_EMBED_MODEL: nomic-embed-text

    volumes:
      - chroma_data:/app/chroma_db
      - uploads_data:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - ollama

    restart: unless-stopped


volumes:
  ollama_data:
  chroma_data:
  uploads_data: